import { copy } from '@wc/copy'
import { Check } from './Check'

/**
 * spec/16 §4 row 2. The picture on the right is a REAL screenshot of the hours
 * grid, regenerated by the Playwright suite in apps/web so it can never drift
 * from the product (19 §8 item 4, 19 §10 item 8). Before session C there was no
 * grid to photograph and 03 §4.1 forbade inventing one; there is now.
 *
 * The heading is the LCP element, not the image: text paints first on a slow
 * connection, which is how 1.5 s on 3G is met (16 §8).
 */
export function Hero() {
  const c = copy.site.hero
  return (
    <section className="border-border-decorative border-b bg-gradient-to-b from-teal-50 to-white px-6 py-14">
      <div className="mx-auto grid max-w-[1160px] items-center gap-11 lg:grid-cols-[1fr_1.1fr]">
        <div>
          <h1 className="font-semibold text-4xl text-text-primary">{c.title}</h1>
          <p className="mt-5 max-w-[520px] text-lg text-text-secondary">{c.subtitle}</p>
          <div className="mt-7 flex flex-wrap gap-3">
            <a
              className="inline-flex h-12 items-center rounded-md bg-brand px-6 font-semibold text-md text-white no-underline hover:bg-brand-hover"
              href="/pricing"
            >
              {c.primary}
            </a>
            <a
              className="inline-flex h-12 items-center rounded-md border border-n-450 bg-white px-6 font-semibold text-md text-n-800 no-underline hover:bg-n-50"
              href="/#output"
            >
              {c.secondary}
            </a>
          </div>
          <ul className="mt-5 flex list-none flex-wrap gap-4 p-0 text-sm text-text-secondary">
            {c.micro.map((line) => (
              <li className="flex items-center gap-1.5" key={line}>
                <Check />
                {line}
              </li>
            ))}
          </ul>
        </div>

        <div className="overflow-hidden rounded-lg border border-n-300 bg-white shadow-panel">
          <img
            src="/hero-grid.png"
            alt={c.shotAlt}
            width={1120}
            height={700}
            className="block h-auto w-full"
          />
        </div>
      </div>
    </section>
  )
}
